#!/usr/bin/env python3
"""Create or rotate the dedicated Hermes Link-to-Agent credential.

The generated value is intentionally never written to stdout.  This utility
only manages its own dedicated environment file; it does not inspect, merge,
or rewrite an existing Hermes Agent or Server configuration file.
"""

from __future__ import annotations

import argparse
import os
import secrets
import stat
import sys
import tempfile
from pathlib import Path


DEFAULT_FILE = Path("/etc/hermes-link-server/internal-agent.env")


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create or rotate the root-only Hermes Link internal credential."
    )
    parser.add_argument(
        "--credential-file",
        type=Path,
        default=DEFAULT_FILE,
        help=f"dedicated environment file (default: {DEFAULT_FILE})",
    )
    parser.add_argument(
        "--hermes-home",
        type=Path,
        required=True,
        help="Hermes Agent metadata directory, for example /home/hermes/.hermes",
    )
    parser.add_argument(
        "--agent-base-url",
        default="http://127.0.0.1:8642",
        help="loopback Hermes Agent origin",
    )
    parser.add_argument(
        "--rotate",
        action="store_true",
        help="replace an existing credential; without this flag an existing file is refused",
    )
    parser.add_argument(
        "--parallel-agent-credential",
        action="store_true",
        help=(
            "write a secondary Agent credential for parallel migration without "
            "overwriting an existing HERMES_LINK_MOBILE_API_TOKEN"
        ),
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="validate and show no secret-free plan only",
    )
    return parser.parse_args()


def _validate_agent_base_url(value: str) -> str:
    normalized = value.strip().rstrip("/")
    if normalized not in {"http://127.0.0.1:8642", "http://localhost:8642"}:
        raise ValueError("Agent base URL must be the loopback Hermes Agent origin")
    return normalized


def _payload(
    *, hermes_home: Path, agent_base_url: str, parallel_agent_credential: bool
) -> bytes:
    token = f"hls_{secrets.token_urlsafe(32)}"
    token_lines = (
        f"HERMES_LINK_AGENT_TOKEN={token}\n"
        f"HERMES_LINK_MOBILE_API_TOKEN_ADDITIONAL={token}\n"
        if parallel_agent_credential
        else f"HERMES_LINK_MOBILE_API_TOKEN={token}\n"
    )
    return (
        "# Generated by Hermes Link Server. Never commit or print this file.\n"
        + token_lines
        + f"HERMES_AGENT_BASE_URL={agent_base_url}\n"
        + f"HERMES_HOME={hermes_home}\n"
    ).encode("utf-8")


def _write_private_file(path: Path, payload: bytes) -> None:
    path.parent.mkdir(mode=0o750, parents=True, exist_ok=True)
    os.chmod(path.parent, 0o750)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", dir=path.parent
    )
    temporary_path = Path(temporary_name)
    try:
        os.chmod(temporary_path, 0o600)
        with os.fdopen(descriptor, "wb") as handle:
            handle.write(payload)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary_path, path)
        os.chmod(path, 0o600)
    finally:
        if temporary_path.exists():
            temporary_path.unlink()


def main() -> int:
    args = _parse_args()
    try:
        agent_base_url = _validate_agent_base_url(args.agent_base_url)
    except ValueError as error:
        print(str(error), file=sys.stderr)
        return 2
    credential_file = args.credential_file.expanduser().resolve()
    hermes_home = args.hermes_home.expanduser().resolve()
    if args.dry_run:
        print(
            f"DRY RUN: create or rotate root-only Hermes Link internal credential at {credential_file}."
        )
        print("DRY RUN: no credential value is generated or printed.")
        return 0
    if credential_file.exists() and not args.rotate:
        print(
            "Dedicated Hermes Link credential already exists; use --rotate to replace it.",
            file=sys.stderr,
        )
        return 1
    _write_private_file(
        credential_file,
        _payload(
            hermes_home=hermes_home,
            agent_base_url=agent_base_url,
            parallel_agent_credential=args.parallel_agent_credential,
        ),
    )
    mode = stat.S_IMODE(credential_file.stat().st_mode)
    if os.name != "nt" and mode != 0o600:
        raise RuntimeError("internal credential file permissions are not 0600")
    print("Hermes Link internal credential was updated. The value was not printed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
